CREATE DATABASE greenlight;

CREATE ROLE greenlight WITH LOGIN PASSWORD 'pa55word';

CREATE EXTENSION IF NOT EXISTS citext;

GRANT CREATE ON DATABASE greenlight TO greenlight;
GRANT CREATE ON SCHEMA public TO greenlight;
GRANT USAGE ON SCHEMA public TO greenlight;
GRANT CONNECT ON DATABASE greenlight TO greenlight;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO greenlight;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO greenlight;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO greenlight;

