version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: greenlight
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: greenlight-api-1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_DSN: ${DB_DSN}
    entrypoint: ["./api", "-db-dsn", "${DB_DSN}"]
    depends_on:
      db:
        condition: service_healthy

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "./migrations", "-database", "${DB_DSN}", "up"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
