apiVersion: v1
kind: ServiceAccount 
metadata:
  name: external-secrets
  namespace: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
#- apiGroups: [""]
#  resources: ["secrets"]
#  verbs: ["get", "list", "watch", "create", "update", "delete"]
#- apiGroups: [""]
#  resources: ["namespaces"]
#  verbs: ["get", "list", "watch"]
#- apiGroups: ["coordination.k8s.io"]
#  resources: ["leases"]
#  verbs: ["get", "watch", "list", "create", "update", "patch"]
#- apiGroups: [""]
#  resources: ["events"]
#  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-role
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: security

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: security
  labels:
    app: external-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets-operator
  template:
    metadata:
      labels:
        app: external-secrets-operator
    spec:
      serviceAccountName: external-secrets
      containers:
      - name: external-secrets-operator
        image: ghcr.io/external-secrets/external-secrets:v0.9.11
        args:
        - --metrics-addr=:8080
        - --enable-leader-election
        env:
        - name: EXTERNAL_SECRETS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9443
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534