apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: greenlight-api
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: postgres-user
    remoteRef:
      key: secret/database/credentials
      property: username
  - secretKey: postgres-password
    remoteRef:
      key: secret/database/credentials
      property: password
  - secretKey: db-dsn
    remoteRef:
      key: secret/database/credentials
      property: dsn