apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: greenlight-api
spec:
  provider:
    vault:
      server: "http://vault.security.svc.cluster.local:8200"
      path: "secret"
      version: "v2" 
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: greenlight-api
type: Opaque
data:
  token: cm9vdA== # "