apiVersion: v1
kind: Namespace
metadata:
  name: greenlight-api
  labels:
    name: greenlight-api
    part-of: greenlight
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    part-of: greenlight
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    part-of: greenlight