apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenlight-api
  namespace: greenlight-api
  labels:
    app: greenlight-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greenlight-api
  template:
    metadata:
      labels:
        app: greenlight-api
    spec:
      nodeSelector:
        type: application
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: greenlight-api
        image: maheshsinghepc/greenlight-api:latest
        command: ["./api"]
        args: ["-db-dsn", "$(DB_DSN)"] 
        ports:
        - containerPort: 4000
        env:
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-dsn
---
apiVersion: v1
kind: Service
metadata:
  name: greenlight-api
  namespace: greenlight-api
spec:
  selector:
    app: greenlight-api
  ports:
  - name: http
    port: 80
    targetPort: 4000
  type: ClusterIP